version: '3'

services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

  downloader:
    build: downloader
    depends_on:
      - nats
      - nats-1
      - nats-2
    environment:
      - SUBJECT=downloader
      - NATS_URI=nats://nats:4222

volumes:
  redis_data:
