version: '3'

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

  # prometheus-nats-exporter:
  #   image: synadia/prometheus-nats-exporter
  #   hostname: prometheus-nats-exporter
  #   command: "-connz -varz -channelz -serverz -subz http://127.0.0.1:8222"
  #   restart: unless-stopped
  #   ports:
  #     - "7777:7777"

  # prometheus:
  #   image: prom/prometheus:latest
  #   hostname: prometheus
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   hostname: grafana
  #   ports:
  #     - "3000:3000"

  downloader:
    build: downloader
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DOWNLOADER_QUEUE=qdownloader
      - DOWNLOAD_DIRECTORY=/data
      - PARSER_SUBJECT=parser
      - NATS_URI=nats://nats:4222
    volumes:
      - output_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  parser:
    build: parser
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DOWNLOADER_QUEUE=qdownloader
      - PARSER_SUBJECT=parser
      - PARSER_QUEUE=qparser
      - NATS_URI=nats://nats:4222
    volumes:
      - output_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  data-manager:
    build: data-manager
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DATA_MANAGER_SUBJECT=data-manager
      - DATA_MANAGER_QUEUE=qdata-manager
      - NATS_URI=nats://nats:4222
      - SCYLLADB=scylla-manager-db
    volumes:
      - output_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  scylla-monitoring:
    image: scylladb/scylla-monitoring:metrics-server
    container_name: scylla-monitoring
    ports:
      - 5556:5556
      - 25826:25826
      - 8080:80
    depends_on:
      - scylla-manager

  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla
    container_name: scylla-manager-db
    ports:
      - 9042:9042

  scylla-manager-db2:
    image: scylladb/scylla
    container_name: scylla-manager-db2
    command: --seeds=scylla-manager-db

  scylla-manager-db3:
    image: scylladb/scylla
    container_name: scylla-manager-db3
    command: --seeds=scylla-manager-db

  scylla-manager-db4:
    image: scylladb/scylla
    container_name: scylla-manager-db4
    command: --seeds=scylla-manager-db

  scylla-manager-db5:
    image: scylladb/scylla
    container_name: scylla-manager-db5
    command: --seeds=scylla-manager-db

  scylla-manager-db6:
    image: scylladb/scylla
    container_name: scylla-manager-db6
    command: --seeds=scylla-manager-db

  scylla-manager-db7:
    image: scylladb/scylla
    container_name: scylla-manager-db7
    command: --seeds=scylla-manager-db


volumes:
  output_data:
