version: '3'

services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
  
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

  downloader:
    build: downloader
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DOWNLOADER_QUEUE=qdownloader
      - DOWNLOAD_DIRECTORY=/data
      - PARSER_SUBJECT=parser
      - NATS_URI=nats://nats:4222
    volumes:
      - output_data:/data

  parser:
    build: parser
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DOWNLOADER_QUEUE=qdownloader
      - PARSER_SUBJECT=parser
      - PARSER_QUEUE=qparser
      - NATS_URI=nats://nats:4222
    volumes:
      - output_data:/data

  data-manager:
    build: data-manager
    depends_on:
      - nats
      - nats-1
      - nats-2
      - scylla-manager
    environment:
      - DOWNLOADER_SUBJECT=downloader
      - DATA_MANAGER_SUBJECT=data-manager
      - DATA_MANAGER_QUEUE=qdata-manager
      - NATS_URI=nats://nats:4222
    volumes:
      - output_data:/data

  scylla-monitoring:
    image: scylladb/scylla-monitoring:metrics-server
    container_name: scylla-monitoring
    ports:
      - 5556:5556
      - 25826:25826
      - 8080:80
    depends_on:
      - scylla-manager

  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla
    container_name: scylla-manager-db
    ports:
      - 9042:9042


volumes:
  redis_data:
  output_data:
